# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c39e88a348becf9ee3b7fdca70178a44300db334f0ac5febda6b79a4c02a03d51fb0c7db90ac7f22602abb89717a0cabc6ff93043f7e3de14133f42ee631488

test:
  secret_key_base: 03f68e4674ad1b2f181838d577ec83d8519a019dee075ae7462df857638ec3a1c27d3c14f30e75b0da2790b1f50666deb45611519bfcbe815acf92f6cc0f5e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
